### ISSUE TITLE
I get a message that the code is not executable due to a problem with the motuclient api

### ISSUE THREAD

**Issue by cafeparade** [CoLAB-ATLANTIC/JUNO#4]
Hello,

I am experiencing an issue with the code provided in this repository. When I attempt to execute the code, I encounter the following error:

`AttributeError: module 'motuclient' has no attribute 'motu_api'`

Upon [investigation](https://github.com/clstoulouse/motu-client-python/issues/35), it appears that the motuclient server might be offline, which may be causing this issue. 

Could anyone provide guidance on how to resolve this problem or suggest any alternative solutions? Any help would be greatly appreciated.

Thank you!

**Comment by Figas23** [comment]
Hello,

I believe the error you were encountering was in the CMEMS_forecast_daily_fronts_netcdf.py script which was still using the motuclient to download data from CMEMS. Motuclient has been deprecated and now we are using the copernicusmarine library.

I believe the problem is now solved.

Kind regards,
Luis
